name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: |
        mkdir -p releng/server-all/target
        cd releng/server-all/target
        echo "File 1" >> file1.txt
        echo "File 2" >> file2.txt
        cd ../../..
    - run: cat releng/server-all/target/test.txt
    - uses: actions/upload-artifact@v3
      with:
        name: releng-folder
        path: releng/

  step1:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: releng-folder
        path: releng
    - run: cat releng/server-all/target/file1.txt

  step2:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: releng-folder
        path: releng
    - run: cat releng/server-all/target/file2.txt

  step3:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: releng-folder
        path: releng
    - run: cat releng/server-all/target/file3.txt

  clean-up:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: 
      - build
      - step1
      - step2
      - step3
    steps:
    - uses: geekyeggo/delete-artifact@v2
      with:
          name: releng-folder
          failOnError: false
