name: Deploy - Dev

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/deploy-generic.yaml
    with:
      awsCommand: s3 ls
    secrets:
      roleToAssume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      awsCommand2: ${{ secrets.AWS_COMMAND }}
